# Generated by Django 5.1.15 on 2026-02-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('dingtalk', '钉钉'), ('email', '邮件')], max_length=20, verbose_name='平台')),
                ('platform_user_id', models.CharField(max_length=100, verbose_name='平台用户ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='用户名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '渠道用户',
                'verbose_name_plural': '渠道用户',
                'unique_together': {('platform', 'platform_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('dingtalk', '钉钉'), ('email', '邮件')], max_length=20, verbose_name='平台')),
                ('content', models.TextField(verbose_name='内容')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件')], default='text', max_length=20, verbose_name='消息类型')),
                ('direction', models.CharField(choices=[('inbound', '收到'), ('outbound', '发出')], default='inbound', max_length=10, verbose_name='方向')),
                ('platform_message_id', models.CharField(blank=True, default='', max_length=200, verbose_name='平台消息ID')),
                ('ai_classification', models.CharField(blank=True, choices=[('urgent', '紧急'), ('important', '重要'), ('normal', '普通'), ('ignore', '可忽略')], default='', max_length=20, verbose_name='AI分类')),
                ('processed', models.BooleanField(default=False, verbose_name='已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('channel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channel.channeluser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['-created_at'],
            },
        ),
    ]
