# Generated by Django 5.1.15 on 2026-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeluser',
            name='platform',
            field=models.CharField(choices=[('dingtalk', '钉钉'), ('email', '邮件'), ('wechat', '企业微信')], max_length=20, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='message',
            name='platform',
            field=models.CharField(choices=[('dingtalk', '钉钉'), ('email', '邮件'), ('wechat', '企业微信')], max_length=20, verbose_name='平台'),
        ),
    ]
