# Generated by Django 5.1.15 on 2026-02-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('priority', models.IntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '普通'), (4, '低')], default=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('done', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('source', models.CharField(choices=[('dingtalk', '钉钉'), ('email', '邮件'), ('manual', '手动')], default='manual', max_length=20, verbose_name='来源')),
                ('source_message_id', models.CharField(blank=True, default='', max_length=200, verbose_name='来源消息ID')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
