# Generated by Django 5.1.15 on 2026-02-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notion_page_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Notion ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, default='迭代事项', max_length=50, verbose_name='任务类型'),
        ),
    ]
