# Generated by Django 5.1.15 on 2026-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_notion_page_id_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, default='其他', max_length=50, verbose_name='任务类型'),
        ),
    ]
